### ISSUE TITLE
Fault address Server Crash

### ISSUE THREAD

**Issue by Jahuty0** [Krypton91/KR_KingOfTheHill#10]
Had my server crash several times last night while sleeping. Only thing in common  with the RPTs is this below.

Mods: @Advanced King of The Hill
Version 1.18.155069
Fault address:  1CC293E4 00:1CC293E4 Unknown module
file:     dayzOffline
world:    chernarusplus
Prev. code bytes: 00 00 48 8B 41 28 48 83 C1 28 F3 0F 10 54 24 78
Fault code bytes: FF 50 50 EB 71 48 8B 41 28 48 83 C1 28 4C 8B C5
=======================================================
note: Minidump has been generated into the file D:\TCAFiles\Users\Paguco\24517\SC\DayZServer_x64_2022-09-11_00-34-56_2022-09-11_01-20-35.mdmp
[DayZServer_x64_2022-09-11_00-34-56_2022-09-11_01-20-35.zip]

Below are the dump file and rpt

(https://github.com/Krypton91/KR_KingOfTheHill/files/9542536/DayZServer_x64_2022-09-11_00-34-56_2022-09-11_01-20-35.zip)

**Comment by Krypton91** [comment]
Hello,

thanks for reporting a crash! 
This crash is not cause king of the hill it just shows you the last loaded mod!
To find out a crash you need to remove specify mods an test the server!
