### ISSUE TITLE
MFSurvival KOTH

### ISSUE THREAD

**Issue by kcorr** [Krypton91/KR_KingOfTheHill#17]
I am the lead dev working on MFSurvival right now. We are using the KOTH mod, but it seems that sometimes only a couple of items will spawn in the chest and not the minimum I have specified. Sometimes no items will spawn in when testing. Could there be an item conflicting this?

We are currently doing 1 KOTH per restart, but have still seen only 3 items spawn and not my minimum #. Please help as soon as possible.

Thank you.

**Comment by Krypton91** [comment]
As you described i think its solved yea? It was because a typo in a classname or?
