### ISSUE TITLE
KOTH Events not despawning

### ISSUE THREAD

**Issue by Jahuty0** [Krypton91/KR_KingOfTheHill#3]
Tested on a no live server, there currently is 0 population. Attached is my config. When a KOTH even spawns it is staying up indefinitely with no player interaction. It never despawns. 1 event on map.

[server-config.txt](https://github.com/Krypton91/KR_KingOfTheHill/files/9387576/server-config.txt)

**Comment by Krypton91** [comment]
Hello, thanks for the report i fixed this issue in the last github commit!
