### ISSUE TITLE
KOTH Marker

### ISSUE THREAD

**Issue by Jahuty0** [Krypton91/KR_KingOfTheHill#4]
KOTH pvez draws a circle even in PVP zones. Also states a marker of AirDrop Here when it spawns.

![image](https://user-images.githubusercontent.com/63546427/185754761-98f183f3-d88b-487f-beea-a066c19937af.png)

**Comment by Krypton91** [comment]
Hello, you need to config this in you PVEZ config.
The mod force a PVP zone everywhere!

**Comment by Jahuty0** [comment]
Attached are my airdrop settings. I also use airdrops so this is on to draw a circle around air drops. For some reason PVEZ thinks KOTH is an airdrop or something.

![image](https://user-images.githubusercontent.com/63546427/186798054-4cd20786-71fb-4402-9fbd-98a7fca190da.png)
