### ISSUE TITLE
PBO Bug

### ISSUE THREAD

**Issue by Crup1er** [Krypton91/KR_KingOfTheHill#5]
every time I leave my server, closing the launcher, this mod gives me a PBO error, I update it and enter normally, the problem is that if you close the launcher and try to enter, it gives me a PBO error again, my server have 40 people by day, we have many complaints about this, any solution?

**Comment by Krypton91** [comment]
Hello, this is not a bug from this mod!
Please verify all mods in your launcher and contact the launcher support!
