### ISSUE TITLE
Please rename the mod

### ISSUE THREAD

**Issue by zamorochilo** [Krypton91/KR_KingOfTheHill#7]
Hello!
There are two mods with the same name on steam, and because of this, players have conflicts if they subscribe to both mods. Two mods don 't get along in the same folder !Workshops, everyone in turn wants to update in the launcher. And because of this confusion, players cannot log in to the server. You can rename the mod so that the two mods get along in the folder!Workshops? Thanks.

**Comment by Krypton91** [comment]
Hello i renamed the mod in the latest update! :)
